name: Check spelling
on: 
  pull_request:
  push: 
      branches:
          - main
jobs:
    spellcheck: 
        runs-on: ubuntu-lastest
        steps: 
          - name: Set up Git repository 
            uses: action/chceckout@v3
          - name: Install dictionaries
            run: |
              npm install @cspell/dict-pl_pl
              npm install @cspell/dict-latex
              npm install @cspell/dict-software-terms
              npm install @cspell/dict-golang
          - name: Run cspell
            uses: streetsidesoftware/cspell-action@v2
            with:
              files: "*.tex"
              chech_dot_files: false
              strict: true
              incremental_file_only: false